# Site settings
title: Catatan harian Firdaus Siregar
description: hanya coretan tangan saya
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://bgdaus.github.io" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Firdaus Siregar
user_description: hanya insan biasa yang ingin terus berkarya
email: fsteamcyber@gmail.com
twitter_username: anak_dayo
github_username:  bgdaus
gplus_username:  bgdaus
disqus_username: bgdaus

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/


# html minify
compress_html:
  clippings: all
  comments: all
  endings: []
  profile: false

# Links to include in menu navigation
# For external links add external: true
links:
  - title: Beranda
    url: /
  - title: Series
    url: /series
  - title: Tagar
    url: /tags
  - title: Tentang Saya
    url: /about
  - title: Kontak
    url: /
# exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules']
